//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreezingMan.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camp
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> CampTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Description { get; set; }
        public Nullable<System.TimeSpan> StartWorkTime { get; set; }
        public Nullable<System.TimeSpan> EndWorkTime { get; set; }
    
        public virtual CampType CampType { get; set; }
        public virtual Status Status { get; set; }
    }
}
